conf.py:
  copyright: 2014
  project: Foundation framework
  version: 1.5.1
  release: 1.5.1
  latex_documents:
  - - Index
    - cb_foundation.tex
    - Foundation framework
    - Charles Brunet
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_use_parts: True
  latex_show_pagerefs: True
  html_theme_options:
     github_repository: cbrunet/typo3-cb_foundation
     github_branch: master