conf.py:
  copyright: 2014
  project: Foundation framework
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - foundation.tex
    - Foundation framework
    - Charles Brunet
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  html_theme_options:
     github_repository: cbrunet/typo3-cb_foundation
     github_branch: master